version: "3"
services:
    db:
        image: "postgres:11.5"
        container_name: "wiph_pg"
        restart: always
        environment: 
            - POSTGRES_USER=$DB_USER
            - POSTGRES_PASS=$DB_PASS
            - POSTGRES_DB=$DB_NAME
        ports:
            - "$DB_PORT:5432"