name: Build and Deploy to Google Cloud Run

on:
    push:
        branches:
          - master
env:
    PROJECT_ID: ${{ secrets.RUN_PROJECT }}
    SERVICE_NAME: ${{ secrets.CLOUD_RUN_SERVICE }}
    RUN_REGION: ${{ secrets.CLOUD_RUN_REGION }}

jobs:
    setup-build-deploy:
        name: Setup, Build, and Deploy
        runs-on: ubuntu-latest
    
        steps:
        - name: Checkout
          uses: actions/checkout@v1

        # Setup gcloud CLI
        - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
          with:
            version: '275.0.0'
            service_account_email: ${{ secrets.SA_EMAIL }}
            service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS}}
    
        # Configure gcloud CLI
        - name: gcloud Set up
          run: |
            gcloud config set project $PROJECT_ID
        # Build and push image to Google Container Registry
        - name: Build
          run: |
            gcloud builds submit -t gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA
        # Deploy image to Cloud Run
        - name: Deploy
          run: |
            gcloud run deploy $SERVICE_NAME \
                --region $RUN_REGION \
                --image gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA \
                --platform managed \
                --allow-unauthenticated
